# Generated by Django 4.2.9 on 2024-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testuser",
            name="user",
        ),
        migrations.AddField(
            model_name="testuser",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testuser",
            name="password",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testuser",
            name="username",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
