# Generated by Django 4.2.9 on 2024-02-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzer", "0002_remove_testuser_user_testuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuser",
                to="quizzer.paper",
            ),
        ),
        migrations.AlterField(
            model_name="usersolution",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uquestion",
                to="quizzer.question",
            ),
        ),
        migrations.AlterField(
            model_name="usersolution",
            name="test_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuser",
                to="quizzer.testuser",
            ),
        ),
    ]
