# Generated by Django 4.2.9 on 2024-02-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzer", "0003_alter_question_paper_alter_usersolution_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qpaper",
                to="quizzer.paper",
            ),
        ),
    ]
