# Generated by Django 4.2.9 on 2024-02-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzer", "0003_paper_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="subject",
            new_name="paper",
        ),
    ]
