# Generated by Django 4.2.9 on 2024-02-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzer", "0004_alter_question_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersolution",
            name="test_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_solution",
                to="quizzer.testuser",
            ),
        ),
    ]
