# Generated by Django 4.2.9 on 2024-02-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzer", "0006_usersolution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersolution",
            name="user",
        ),
        migrations.AddField(
            model_name="usersolution",
            name="test_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzer.testuser",
            ),
            preserve_default=False,
        ),
    ]
